In [1]:
#import libraries
import numpy as np
import pandas as pd

In [2]:
# importing dataset of calories and converting it into pandas data frame
df_calories = pd.read_csv('calories_exercise/calories.csv')

In [3]:
df_calories.head()

    User_ID  Calories
0  14733363     231.0
1  14861698      66.0
2  11179863      26.0
3  16180408      71.0
4  17771927      35.0

In [4]:
# importing dataset of exercise and converting it into pandas data frame
df_exercise = pd.read_csv("calories_exercise/exercise.csv")

In [5]:
df_exercise.head()

    User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0  14733363    male   68   190.0    94.0      29.0       105.0       40.8
1  14861698  female   20   166.0    60.0      14.0        94.0       40.3
2  11179863    male   69   179.0    79.0       5.0        88.0       38.7
3  16180408  female   34   179.0    71.0      13.0       100.0       40.5
4  17771927  female   27   154.0    58.0      10.0        81.0       39.8

In [6]:
# joining both the datasets
df = pd.merge(df_exercise, df_calories, on='User_ID', how='inner')
df

,User_ID,Gender,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Calories
0,14733363,male,68,190.0,94.0,29.0,105.0,40.8,231.0
1,14861698,female,20,166.0,60.0,14.0,94.0,40.3,66.0
2,11179863,male,69,179.0,79.0,5.0,88.0,38.7,26.0
3,16180408,female,34,179.0,71.0,13.0,100.0,40.5,71.0
4,17771927,female,27,154.0,58.0,10.0,81.0,39.8,35.0
...,...,...,...,...,...,...,...,...,...
14995,15644082,female,20,193.0,86.0,11.0,92.0,40.4,45.0
14996,17212577,female,27,165.0,65.0,6.0,85.0,39.2,23.0
14997,17271188,female,43,159.0,58.0,16.0,90.0,40.1,75.0
14998,18643037,male,78,193.0,97.0,2.0,84.0,38.3,11.0
14999,11751526,male,63,173.0,79.0,18.0,92.0,40.5,98.0

#### Converting Text data into numerical data

In [7]:
df.replace({"Gender":{"male":0,"female":1}}, inplace=True)

C:\Users\Rishabh\AppData\Local\Temp\ipykernel_9280\3500960956.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace({"Gender":{"male":0,"female":1}}, inplace=True)

Separating Features and Target

In [8]:
X = df.drop(columns=['User_ID',"Calories"], axis=1)
Y = df['Calories']

In [9]:
print(X)

       Gender  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0           0   68   190.0    94.0      29.0       105.0       40.8
1           1   20   166.0    60.0      14.0        94.0       40.3
2           0   69   179.0    79.0       5.0        88.0       38.7
3           1   34   179.0    71.0      13.0       100.0       40.5
4           1   27   154.0    58.0      10.0        81.0       39.8
...       ...  ...     ...     ...       ...         ...        ...
14995       1   20   193.0    86.0      11.0        92.0       40.4
14996       1   27   165.0    65.0       6.0        85.0       39.2
14997       1   43   159.0    58.0      16.0        90.0       40.1
14998       0   78   193.0    97.0       2.0        84.0       38.3
14999       0   63   173.0    79.0      18.0        92.0       40.5

[15000 rows x 7 columns]

In [10]:
pip install --upgrade xgboost scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: xgboost in c:\users\rishabh\appdata\roaming\python\python312\site-packages (3.0.5)
Requirement already satisfied: scikit-learn in c:\users\rishabh\appdata\roaming\python\python312\site-packages (1.7.2)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\rishabh\appdata\roaming\python\python312\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn import metrics

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

In [13]:
print(X.shape, X_train.shape, X_test.shape)

(15000, 7) (12000, 7) (3000, 7)

### XGBoost Regressor

In [14]:
#loading the model
model = XGBRegressor()

In [15]:
#training the model with X_train
model.fit(X_train, Y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

### Evaluation

In [16]:
# prediction on train data
train_data_prediction = model.predict(X_train)

In [17]:
print(train_data_prediction)

[ 11.680271  36.71814   31.747328 ... 108.05978  179.23735   44.236874]

In [18]:
# prediction on test data
test_data_prediction = model.predict(X_test)

In [19]:
print(test_data_prediction)

[125.58828  222.11377   38.725952 ... 144.3179    23.425894  90.100494]

### Mean Absolute Error

In [20]:
from sklearn import metrics
from sklearn.metrics import r2_score

In [21]:
mae = metrics.mean_absolute_error(Y_test, test_data_prediction)

In [22]:
print("Mean Absolute Error = ", mae)

Mean Absolute Error =  1.4833678883314132

In [23]:
lossy = r2_score(Y_test, test_data_prediction)
lossy

0.998800624504713

In [24]:
lossy2 = r2_score(Y_train, train_data_prediction)
lossy2

0.9995691477017405